// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

// Source: https://inference.poolside.ai/docs
export const POOLSIDE_MODELS = {
	"poolside/laguna-xs.2": {
		id: "poolside/laguna-xs.2",
		name: "Poolside Laguna XS 2",
		api: "openai-completions",
		provider: "poolside",
		baseUrl: "https://inference.poolside.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.30,
			output: 0.30,
			cacheRead: 0.30,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 4096,
	} satisfies Model<"openai-completions">,
	"poolside/laguna-m.1": {
		id: "poolside/laguna-m.1",
		name: "Poolside Laguna M 1",
		api: "openai-completions",
		provider: "poolside",
		baseUrl: "https://inference.poolside.ai/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false},
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.50,
			output: 0.50,
			cacheRead: 0.50,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 4096,
	} satisfies Model<"openai-completions">,
} as const;
